# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 06:14
from __future__ import unicode_literals

from django.db import migrations, models
# import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                # ('position', geoposition.fields.GeopositionField(default='0,0', max_length=42)),
            ],
        ),
    ]
