# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0003_location_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='location',
            new_name='pass_location',
        ),
    ]
