# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0004_auto_20180806_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_location',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
